server:
  port: 8000
spring:
  application:
    name: crowd-pay
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.56.103
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlLOEDjnRziqGb7NXPjo32yYCYkx+YI3ySQ5E5Ma0DWt1eZ8V/alRvuIvUSZHIeSDo4bVC6a9mcmHmwow5sVbD4iWPqvvTOqpXeldLmXr4IguAClUMbWjBB3PTDlO1wvIKP5reihvajn9YnVFIYysPHIW1NNut3Q7wTSzv996vBI5BbdbLpJwkTvhLSjvkYlfb/kRvklm8LvPqYcEYPEreWBZG7VcYckp6McBmJc8P8Qmpe3uW44HZmhLY6OKH5fWFHWjc4/apyIDY3Pc8/ZHphvnPOJw9vL8Ww9ZGMXvXQe+OWAOxVzFgiR+LJk+FvijuFQtXXCdm4GsD1pyrtepvQIDAQAB
    app-id: 2021000116685915
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCMBATjrSmnd7ndp/CU6LT6R/bQZ6MfzxBE67F1xxzOd+yBZYQQcqPMp2RTBO9g8gJxHQXIEvG0C3+mhRomaDwzjuZh6BQJcvpLI5isyeVbZsml+CURcOoqOjWj9Vr+h4IXZ7HNExzWEhPsGZVC2n3chRc3WJCrNhkVx6AEmI34u/0xIDDoHRf4TDIYpqxhvSctTXDZgufMPZSJDbHMxff2Jqci7BWzMRDiihqRLUOSpMDyHoxPwn5NSKQDpZ1GdbLnrfC0oESf3LSEF6ohH03XgvZeeAZmQvkyT1PqZSa+Un73AfCz7H4vP++fzTMCdoL2KimiBvtSmOgWBU5p2glPAgMBAAECggEAGfbQ1UuSMtzv2Zu/8E0q6lKYAVOGm2pxcOZoFRgkTmFMuT4S/F3V5CiSYRbEMS0PqNwh61Uf/yw2srFyBPdFWqZAMJ2xwYLRyUdDk58o6gcok59teEuBEO2UbuAbzKFiTWbMQOQvb78QdLLVy/zqZA9GG9xPj4BLrI9FLDUB9sLXU5qorwHIeHk3fAR4IDfX8CLfZySZ5QOu994Exvc751HECC6DXnoUB0wOm+SjKpnJUWhCQPtO/R4JevcpUQLrnw6y7GoMOdQ/v2iHJVXMUt+Rgv4BqNHs55bBt4kVmHelHjoxitux2h1GSm0LwaAuL7k0q1E/Mzpc+F4SppPfUQKBgQDDT6kdgiZ9E7dD35N3nyyjJE0HqmFWwNKWzfZ1stNQAFe0SSYbik4/dlfNd3sy1tYgNbLQKggB/Rw3t5YvCzWJlSx1fdJQpHiJfivfavPi5otPQyoBw185HafrC07xss/iA2HDL0d41usY4FAbRizaxDScH+TTSuR2O5L3yyrkhwKBgQC3hcqnmI0PgIJ6jSqgiK3gclm2zrJSo0hcbSbEWTnmXQhdH5zTfCqox+O7SoogFbZntar/4vZfkmaMlt5oLqYfYVQhGL7mOrOySYMWnF3P08uDlGUnkLgxttaxj0wxg/l4HLIGRf43FTzLodKHDHDB1T6z0GltuS9E6CNILUKu+QKBgFF9W0JEm2p0X3KiRhUTBLzM2JbqL9LSgQsKxFo3UpN+kRlXq96xxhQUfG3t/CkqGg02WnUgFFdAFBXrM25NbvkIlJQw+x9KgEBdtFBzf26cYmOf0lcJ/SEHjpgzD60ovjO+1XtqrpdslIq8jK/Uh8J/OrQpWoAOL2RlVtysmCjhAoGAVhNIU4b3UjgB+pzPS3APrV+0uEsF1ECFJeSD9D+tKmCkFZlIIuDv2S23oBZ75kSIwuewBkhbKcQumO4B7ndCryElJkjG8JDDy3EzLJ22Wk2J/HLTZtU3rwmEdM8y+15c2XsL/GlDrG4nj5KcfX7WO/Nab1fmuvHKO9VtBuNDjXECgYA2u56EV/juVQMItt4RDwE/oRDQnopGpM8VkrOA5mOT2P6IsoJBn/D65yiGwpG485qtH+Y5coag/Wn3YYhnanTYTROX4uauvMeYtyvD58KQm0+g1DsDXHpg2zWF3EV27McwJ4VJ8+f4gzTDLvgnmBkduIwy5mA+S97atwzCAyXQ9w==
#    notify-url: http://kmpkt9.natappfree.cc/pay/notify
    notify-url: http://localhost/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
