server:
  port: 8000
spring:
  application:
    name: crowd-pay
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.56.103
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: **********
    app-id: 2021000116685915
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: **********
#    notify-url: http://kmpkt9.natappfree.cc/pay/notify
    notify-url: http://localhost/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
