package com.it.crowd.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbg.generated Sat Dec 19 10:26:25 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.name
     *
     * @mbg.generated Sat Dec 19 10:26:25 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.title
     *
     * @mbg.generated Sat Dec 19 10:26:25 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.category_id
     *
     * @mbg.generated Sat Dec 19 10:26:25 CST 2020
     */
    private Integer categoryId;
}