package com.it.crowd.entity;

import lombok.Data;

@Data
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.name
     *
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.name
     *
     * @return the value of t_role.name
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.name
     *
     * @param name the value for t_role.name
     * @mbg.generated Fri Dec 11 10:13:17 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Role() {
        super();
    }

    public Role(Integer id, String name) {
        this.id = id;
        this.name = name;
    }
}