server:
  port: 5000
spring:
  application:
    name: crowd-project
  redis:
    host: 192.168.56.103
    session:
      store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: *******
    access-key-secret: *********
    bucket-domain: http://*****.aliyuncs.com
    bucket-name: ******
    end-point: http://*****.aliyuncs.com
